# Generated by Django 5.2.5 on 2025-08-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_classifier', '0003_rename_date_of_birth_profile_dob_alter_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
